### PR TITLE
Copy all shared-libs instead 

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

An alternative to depending on npm to correctly map local scoped dependencies. 
We do not add our shared libraries as dependencies in our `package.json`s any more.
For development, the libs are symlinked into `node_modules` by grunt - like `npm ci` would do. 
For creating packages, both `api` and `sentinel` have a new property in their `package.json` that should list the shared-libs that the module uses and must be bundled.

Build sizes here:
https://staging.dev.medicmobile.org/_couch/_utils/document.html?builds/medic:medic:5739-with-links

| Version                                                                                                   | api    | sentinel | compiled.json |
|-----------------------------------------------------------------------------------------------------------|--------|----------|---------------|
| [3.5.x](https://staging.dev.medicmobile.org/_couch/_utils/document.html?builds/medic:medic:3.5.x)         | 3.7 MB | 2.9 MB   | 20.1 MB       |
| [master](https://staging.dev.medicmobile.org/_couch/_utils/document.html?builds/medic:medic:master)       | 3.8 MB | 2.9 MB   | 19.0 MB        |
| [this PR](https://staging.dev.medicmobile.org/_couch/_utils/document.html?builds/medic:medic:5739-with-links) | 3.8 MB  | 2.9 MB   | 19.0 MB       |

#5739 

# Code review items

- Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
WTB honest review, @garethbowen . Many thanks!

**Comment by dianabarsan** [comment]
@garethbowen 

> but it just feels untidy, you know 

yup

>  If it's not too much trouble can we add a new property to the package.json called sharedLibs

I actually considered this quite a lot, but my instinct was not to add custom properties to package.json. stupid instinct :D

> what if we only ran the copy in ci and never in dev ... add all the shared libs as file dependencies in the root package.json

Will give that a try!

**Comment by dianabarsan** [comment]
> what if we only ran the copy in ci and never in dev ... add all the shared libs as file dependencies in the root package.json

Well, this ends up being really finicky and seems prone to errors of npm not managing to map symlinks correctly (like it happened here: https://travis-ci.org/medic/medic/jobs/549514924). 
For development, I ended up symlinking manually. 
For deployments, I still copy all libs (for simplicity) but added a new property in the modules `package.json` that lists which shared-libs to bundle, that I use when updating `bundledDependencies`.

**Comment by garethbowen** [comment]
> For development, I ended up symlinking manually.

That's ok. Currently it looks like it's symlinking in ci too. I guess it's being ignored because the copy is found before the link.

> For deployments, I still copy all libs (for simplicity) but added a new property in the modules package.json that lists which shared-libs to bundle, that I use when updating bundledDependencies.

Perfect!

**Pull request merged**
