### PR TITLE
Fixes UHC visits muted contacts colors.

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Updates muted contacts styling.

medic/medic#5595

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Old styling:

image

New styling:

image

**Comment by dianabarsan** [comment]
Please review, @wtekeu . Thank you!

**Comment by dianabarsan** [comment]
@wtekeu Can you please have a look? Thanks!

**Comment by wtekeu** [comment]
Merged https://github.com/medic/medic/pull/5600 into master.

**Pull request merged**
