### PR TITLE
A stripped (reduced) version of angular.copy

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Creates `@medic/utils` shared library with first "component": a deep clone function with decent performance. 

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by dianabarsan** [comment]
@garethbowen I've ported the function from Angular. Do you think it's worth integrating ? 
Thanks, in advance, for your time.

**Comment by dianabarsan** [comment]
We only clone in a few places (under 5 - but will check in depth), I did add a smaller perf test in the PR where I clone a doc that is a sort of exceprt of `settings` (comparing to JSON functions), but I can do on a collection of random couchdb docs (which is what we, indeed, usually clone).

**Comment by dianabarsan** [comment]
List of places we use `JSON` cloning: 
[Changes controller](https://github.com/medic/medic/blob/master/api/src/controllers/changes.js#L88)
[Lineage 1](https://github.com/medic/medic/blob/master/shared-libs/lineage/src/lineage.js#L70)
[Lineage 2](https://github.com/medic/medic/blob/master/shared-libs/lineage/src/lineage.js#L352)
[Target Generator](https://github.com/medic/medic/blob/master/webapp/src/js/services/target-generator.js#L94)
[Unmerged transitions shared lib](https://github.com/medic/medic/pull/5476/files#diff-10b282525787acf534dcd78f962c710eR78)

We could also use this in Redux reducers (which need to be pure functions) to clone previous state properties (once the state becomes complicated enough).

**Comment by garethbowen** [comment]
@dianabarsan Is this still worth doing?

**Comment by dianabarsan** [comment]
I think lodash's deepCopy is good enough :)

**Pull request closed without merging**
