### PR TITLE
Fix a bug where edit translation failed silently

### PR DESCRIPTION
**Pull request by garethbowen**
Also makes the translation key required when adding a translation.
Also changes the translation list to show the key with styling when the translation is missing for that key.

medic/medic#5405
medic/medic#5120
medic/medic#5121

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
@Jodge Can I get a code review please?

**Comment by Jodge** [comment]
@garethbowen I realised when saving a new translation i.e. without setting the "terms" it silently fails (not being saved) i.e. Doesn't prompt user to enter at least one term. Is that the expected behaviour?

**Comment by garethbowen** [comment]
@Jodge What I expect is that only the key will be required, so if you only enter the key it should be saved (once this PR is merged). This may not be everyone's expected behaviour...

When you say "silently fails" do you mean the old code or the PR code?

**Comment by Jodge** [comment]
In the PR Code, saving a translation key without entering any Language for it results in it not being displayed on the List after saving.

**Comment by garethbowen** [comment]
@Jodge Well that's definitely a fail! I'll see if I can reproduce that.

**Comment by garethbowen** [comment]
@Jodge Ok, can you try that again?

Thanks.

**Comment by garethbowen** [comment]
Oh man, I ran karma locally but I think I ran `karma:unit` not `karma:admin`. Thanks for fixing that!

**Pull request merged**
