### PR TITLE
Corrects error message being displayed

### PR DESCRIPTION
**Pull request by wtekeu**
# Description

Corrects error message being displayed
Screen Shot 2019-10-16 at 5 06 17 PM

medic/medic#6020

# Code review items

- Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- Documented: Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by wtekeu** [comment]
Thanks for the review. I will add a test.
As for the translation, I did add the translation https://github.com/medic/medic/pull/6030/files#diff-d4c9274f77952a69e8179b79eda66c70R179

**Comment by dianabarsan** [comment]
I know you added the translation for English, but if you switch to another language that is lacking the translation, that's the behavior that you will see. I guess I'm requesting to edit that service to catch translation errors :)

**Comment by wtekeu** [comment]
@dianabarsan It looks like it defaults to the English one:
Screen Shot 2019-10-21 at 1 16 38 PM

(added the test and catch logic)

**Comment by dianabarsan** [comment]
Yea, you're right, for French it does appear to work. I was using a custom translation in this case, one that I had created before and the behavior is the same, except the exception is caught and displayed in the console:

image

image

I think it's a separate issue to check why translations aren't working the same for custom languages.

**Pull request merged**
